#!/bin/bash
#
# Let's Encrypt SSL Certificate Setup Script for FerryTrmnl
# This script installs certbot, generates SSL certificates, configures nginx,
# and sets up automatic certificate renewal.
#
# Usage: sudo ./deployment/setup-letsencrypt.sh
#
# Prerequisites:
# - Ubuntu/Debian-based system
# - nginx installed
# - Domain pointed to this server's IP
# - .env file configured with LETSENCRYPT_DOMAIN and LETSENCRYPT_EMAIL
#

set -e

# Color output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Get script directory and project root
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

echo -e "${BLUE}"
echo "=============================================="
echo "  FerryTrmnl Let's Encrypt SSL Setup"
echo "=============================================="
echo -e "${NC}"

# Check if running as root
if [[ $EUID -ne 0 ]]; then
    echo -e "${RED}Error: This script must be run as root (use sudo)${NC}"
    exit 1
fi

# Change to project root
cd "$PROJECT_ROOT"

# Check if .env file exists
if [ ! -f .env ]; then
    echo -e "${RED}Error: .env file not found!${NC}"
    echo "Please copy .env.template to .env and configure it first."
    exit 1
fi

# Load environment variables
source .env

# Validate required environment variables
if [ -z "$LETSENCRYPT_DOMAIN" ]; then
    echo -e "${RED}Error: LETSENCRYPT_DOMAIN not set in .env${NC}"
    echo "Please add your domain (e.g., ferry.yourdomain.com) to .env"
    exit 1
fi

if [ -z "$LETSENCRYPT_EMAIL" ]; then
    echo -e "${RED}Error: LETSENCRYPT_EMAIL not set in .env${NC}"
    echo "Please add your email address for Let's Encrypt notifications to .env"
    exit 1
fi

DOMAIN="$LETSENCRYPT_DOMAIN"
EMAIL="$LETSENCRYPT_EMAIL"
FLASK_PORT="${FLASK_PORT:-5050}"

echo -e "${GREEN}Configuration:${NC}"
echo "  Domain: $DOMAIN"
echo "  Email: $EMAIL"
echo "  Flask Port: $FLASK_PORT"
echo ""

# Detect package manager
if command -v apt-get &> /dev/null; then
    PKG_MANAGER="apt"
elif command -v dnf &> /dev/null; then
    PKG_MANAGER="dnf"
elif command -v yum &> /dev/null; then
    PKG_MANAGER="yum"
else
    echo -e "${RED}Error: Unsupported package manager. This script supports apt, dnf, and yum.${NC}"
    exit 1
fi

echo -e "${YELLOW}Step 1: Installing certbot and nginx plugin...${NC}"

case $PKG_MANAGER in
    apt)
        apt-get update
        apt-get install -y certbot python3-certbot-nginx
        ;;
    dnf)
        dnf install -y certbot python3-certbot-nginx
        ;;
    yum)
        yum install -y epel-release
        yum install -y certbot python3-certbot-nginx
        ;;
esac

echo -e "${GREEN}Certbot installed successfully.${NC}"
echo ""

echo -e "${YELLOW}Step 2: Checking nginx installation...${NC}"

if ! command -v nginx &> /dev/null; then
    echo -e "${RED}Error: nginx is not installed. Please install nginx first.${NC}"
    exit 1
fi

# Check if nginx is running
if ! systemctl is-active --quiet nginx; then
    echo -e "${YELLOW}Starting nginx...${NC}"
    systemctl start nginx
fi

echo -e "${GREEN}nginx is running.${NC}"
echo ""

echo -e "${YELLOW}Step 3: Creating nginx configuration for $DOMAIN...${NC}"

# Create nginx configuration
NGINX_CONF="/etc/nginx/sites-available/ferrytrmnl"
NGINX_ENABLED="/etc/nginx/sites-enabled/ferrytrmnl"

# Check if sites-available directory exists (Debian/Ubuntu style)
if [ -d "/etc/nginx/sites-available" ]; then
    NGINX_CONF_DIR="/etc/nginx/sites-available"
    NGINX_ENABLED_DIR="/etc/nginx/sites-enabled"
else
    # RHEL/CentOS style - use conf.d
    NGINX_CONF_DIR="/etc/nginx/conf.d"
    NGINX_ENABLED_DIR=""
    NGINX_CONF="/etc/nginx/conf.d/ferrytrmnl.conf"
fi

# Create initial HTTP-only config for certbot challenge
cat > "$NGINX_CONF" << EOF
# FerryTrmnl nginx configuration
# Generated by setup-letsencrypt.sh

# HTTP server - used for Let's Encrypt challenge and redirect
server {
    listen 80;
    listen [::]:80;
    server_name $DOMAIN;

    # Let's Encrypt challenge location
    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    # Redirect all other HTTP traffic to HTTPS (after cert is installed)
    location / {
        return 301 https://\$server_name\$request_uri;
    }
}
EOF

# Enable the site (Debian/Ubuntu style)
if [ -n "$NGINX_ENABLED_DIR" ] && [ ! -L "$NGINX_ENABLED_DIR/ferrytrmnl" ]; then
    ln -sf "$NGINX_CONF" "$NGINX_ENABLED_DIR/ferrytrmnl"
fi

# Test nginx configuration
nginx -t

# Reload nginx
systemctl reload nginx

echo -e "${GREEN}nginx configured for initial HTTP setup.${NC}"
echo ""

echo -e "${YELLOW}Step 4: Obtaining Let's Encrypt certificate...${NC}"

# Create webroot directory if it doesn't exist
mkdir -p /var/www/html

# Obtain certificate using webroot method
certbot certonly \
    --webroot \
    --webroot-path=/var/www/html \
    --email "$EMAIL" \
    --agree-tos \
    --no-eff-email \
    -d "$DOMAIN"

if [ $? -ne 0 ]; then
    echo -e "${RED}Error: Failed to obtain certificate.${NC}"
    echo "Please ensure:"
    echo "  1. Your domain ($DOMAIN) points to this server's IP"
    echo "  2. Port 80 is accessible from the internet"
    echo "  3. No firewall is blocking HTTP traffic"
    exit 1
fi

echo -e "${GREEN}SSL certificate obtained successfully!${NC}"
echo ""

echo -e "${YELLOW}Step 5: Configuring nginx with SSL...${NC}"

# Update nginx configuration with full SSL setup
cat > "$NGINX_CONF" << EOF
# FerryTrmnl nginx configuration
# Generated by setup-letsencrypt.sh
# SSL certificate managed by Let's Encrypt

# HTTP server - redirects to HTTPS
server {
    listen 80;
    listen [::]:80;
    server_name $DOMAIN;

    # Let's Encrypt challenge location (for renewals)
    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    # Redirect all HTTP traffic to HTTPS
    location / {
        return 301 https://\$server_name\$request_uri;
    }
}

# HTTPS server
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name $DOMAIN;

    # SSL certificate files from Let's Encrypt
    ssl_certificate /etc/letsencrypt/live/$DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$DOMAIN/privkey.pem;

    # SSL configuration - modern settings
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384';
    ssl_prefer_server_ciphers off;

    # SSL session settings
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:50m;
    ssl_session_tickets off;

    # OCSP stapling
    ssl_stapling on;
    ssl_stapling_verify on;
    ssl_trusted_certificate /etc/letsencrypt/live/$DOMAIN/chain.pem;
    resolver 8.8.8.8 8.8.4.4 valid=300s;
    resolver_timeout 5s;

    # Security headers
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    # Logging
    access_log /var/log/nginx/ferrytrmnl_access.log;
    error_log /var/log/nginx/ferrytrmnl_error.log;

    # Max body size
    client_max_body_size 1M;

    # Proxy settings for Flask/Gunicorn
    location / {
        proxy_pass http://127.0.0.1:$FLASK_PORT;

        # Proxy headers
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Forwarded-Host \$host;
        proxy_set_header X-Forwarded-Port \$server_port;

        # Proxy timeouts
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;

        # Buffering
        proxy_buffering on;
        proxy_buffer_size 4k;
        proxy_buffers 8 4k;
        proxy_busy_buffers_size 8k;

        # Don't pass these headers to backend
        proxy_hide_header X-Powered-By;
    }

    # Health check endpoint
    location /health {
        proxy_pass http://127.0.0.1:$FLASK_PORT/health;
        access_log off;
    }
}
EOF

# Test nginx configuration
nginx -t

# Reload nginx with new SSL configuration
systemctl reload nginx

echo -e "${GREEN}nginx configured with SSL successfully!${NC}"
echo ""

echo -e "${YELLOW}Step 6: Setting up automatic certificate renewal...${NC}"

# Certbot automatically installs a systemd timer or cron job
# Let's verify it's set up and add a post-renewal hook to reload nginx

# Create renewal hook to reload nginx after certificate renewal
HOOK_DIR="/etc/letsencrypt/renewal-hooks/deploy"
mkdir -p "$HOOK_DIR"

cat > "$HOOK_DIR/reload-nginx.sh" << 'EOF'
#!/bin/bash
# Reload nginx after certificate renewal
systemctl reload nginx
EOF

chmod +x "$HOOK_DIR/reload-nginx.sh"

# Test if systemd timer is enabled
if systemctl list-timers | grep -q certbot; then
    echo -e "${GREEN}Certbot systemd timer is active.${NC}"
    systemctl status certbot.timer --no-pager || true
else
    # Fall back to checking/creating cron job
    if [ -f /etc/cron.d/certbot ]; then
        echo -e "${GREEN}Certbot cron job is configured.${NC}"
    else
        # Create cron job for renewal
        echo "0 0,12 * * * root certbot renew --quiet --deploy-hook '/etc/letsencrypt/renewal-hooks/deploy/reload-nginx.sh'" > /etc/cron.d/certbot
        echo -e "${GREEN}Created cron job for certificate renewal.${NC}"
    fi
fi

echo ""
echo -e "${YELLOW}Step 7: Testing certificate renewal (dry run)...${NC}"

certbot renew --dry-run

if [ $? -eq 0 ]; then
    echo -e "${GREEN}Certificate renewal test passed!${NC}"
else
    echo -e "${YELLOW}Warning: Renewal dry-run had issues. Please check certbot logs.${NC}"
fi

echo ""
echo -e "${BLUE}=============================================="
echo "  Setup Complete!"
echo "==============================================${NC}"
echo ""
echo -e "${GREEN}Your FerryTrmnl server is now secured with Let's Encrypt SSL!${NC}"
echo ""
echo "Summary:"
echo "  - Domain: https://$DOMAIN"
echo "  - Certificate location: /etc/letsencrypt/live/$DOMAIN/"
echo "  - nginx config: $NGINX_CONF"
echo "  - Auto-renewal: Enabled (runs twice daily)"
echo ""
echo "Useful commands:"
echo "  - Check certificate expiry: sudo certbot certificates"
echo "  - Manual renewal: sudo certbot renew"
echo "  - Test nginx config: sudo nginx -t"
echo "  - Reload nginx: sudo systemctl reload nginx"
echo "  - View nginx logs: sudo tail -f /var/log/nginx/ferrytrmnl_*.log"
echo ""
echo -e "${YELLOW}Note: Make sure your Flask/Gunicorn application is running on port $FLASK_PORT${NC}"
echo ""
